ci: use apt-fast and provide two mirrors

diff --git a/.github/actions/install-deps-action/action.yml b/.github/actions/install-deps-action/action.yml
--- a/.github/actions/install-deps-action/action.yml
+++ b/.github/actions/install-deps-action/action.yml
@@ -3,34 +3,95 @@ name: install-deps
 runs:
   using: 'composite'
   steps:
-    # The Azure apt repos are pretty terrible and keep timing out. Use this
-    # GitHub action to select a fast one.
-    - name: Configure fast APT mirror
-      uses: vegardit/fast-apt-mirror.sh@1.4.1
-      with:
-        exclude-current: true # the azure repo is so unstable we should never use it
+    # The Azure apt repos are pretty terrible and keep timing out. Selecting a
+    # single fast mirror also fails sometimes when we apply significant load.
+    # Select a fast non-Azure mirror and use `apt-fast` to balance between two
+    # mirrors.
+    - name: Configure apt-metalink with fast APT mirror
+      run: |
+        sudo curl https://raw.githubusercontent.com/vegardit/fast-apt-mirror.sh/v1/fast-apt-mirror.sh -o /usr/local/bin/fast-apt-mirror.sh
+        sudo curl https://raw.githubusercontent.com/tatsuhiro-t/apt-metalink/refs/heads/master/apt-metalink -o /usr/local/bin/apt-metalink
+        sudo chmod 755 /usr/local/bin/fast-apt-mirror.sh /usr/local/bin/apt-metalink
+
+        # establish country to fast-apt-mirror.sh gets a default set of options
+        IP_ADDRESS=$(curl -s http://checkip.amazonaws.com)
+        COUNTRY_CODE=$(curl -s http://ip-api.com/json/$IP_ADDRESS | jq -r '.countryCode')
+        echo "Detected country code: $COUNTRY_CODE"
+
+        FAST_MIRROR=$(fast-apt-mirror.sh find \
+            --exclude-current \
+            --country "$COUNTRY_CODE" \
+            --healthchecks 20 \
+            --speedtests 10 \
+            --parallel 2 \
+        )
+        sudo add-apt-repository -y "deb $FAST_MIRROR $(lsb_release -cs) main restricted universe multiverse"
+        sudo apt-get update
+
+        # for apt-metalink
+        sudo apt-get install -y aria2 python3-apt
+
+      shell: bash
 
     ### OTHER REPOS ####
-    # turn off interactive, refresh pkgs
+    # turn off interactive and remove package sets
     - run: |
         sudo rm /var/lib/man-db/auto-update
-        sudo apt-get update
-        sudo apt-get install -y tasksel
+        sudo apt-metalink install tasksel
         sudo tasksel remove ubuntu-desktop
       shell: bash
 
     ### DOWNLOAD AND INSTALL DEPENDENCIES ###
 
-    # Download dependencies packaged by Ubuntu
+    # Download dependencies packaged by Ubuntu. This command regularly failed
+    # before so we aggressively tune aria2c to hit multiple mirrors with retries
+    # to ensure it succeeds.
     - run: |
-        sudo apt-get install -f -y bison busybox-static cmake coreutils \
-        cpio elfutils file flex gcc gcc-multilib git iproute2 jq kbd kmod \
-        libcap-dev libelf-dev libunwind-dev libvirt-clients libzstd-dev \
-        linux-headers-generic linux-tools-common linux-tools-generic make \
-        ninja-build pahole pkg-config python3-dev python3-pip python3-requests \
-        qemu-kvm rsync stress-ng udev zstd libseccomp-dev libcap-ng-dev \
-        llvm-19 clang-19 python3-full curl meson bpftrace dwarves rustup \
-        protobuf-compiler
+        sudo apt-metalink --metalink-out=/tmp/packages.metalink.xml install \
+        bison busybox-static cmake coreutils cpio elfutils file flex gcc \
+        gcc-multilib git iproute2 jq kbd kmod libcap-dev libelf-dev libunwind-dev \
+        libvirt-clients libzstd-dev linux-headers-generic linux-tools-common \
+        linux-tools-generic make ninja-build pahole pkg-config python3-dev \
+        python3-pip python3-requests qemu-system-x86 rsync stress-ng udev zstd \
+        libseccomp-dev libcap-ng-dev llvm-19 clang-19 python3-full curl meson \
+        bpftrace dwarves rustup protobuf-compiler
+
+        MAX_ATTEMPTS=5
+        BACKOFF=5
+
+        PKG_TMPDIR=$(mktemp -d)
+        for attempt in $(seq 1 $MAX_ATTEMPTS); do
+          echo "aria2c attempt $attempt/$MAX_ATTEMPTS…"
+          aria2c \
+            --metalink-file=/tmp/packages.metalink.xml \
+            --dir="$PKG_TMPDIR" \
+            --file-allocation=none \
+            --continue=true \
+            --split=4 \
+            --stream-piece-selector=random \
+            --min-split-size=1M \
+            --max-connection-per-server=1 \
+            --max-tries=32 \
+            --lowest-speed-limit=1k \
+            --retry-wait=5 \
+            --timeout=10 \
+            --connect-timeout=5 \
+            --no-conf && break
+
+            if [ $attempt -lt $MAX_ATTEMPTS ]; then
+              echo "aria2c failed, sleeping $BACKOFF seconds before retry…"
+              sleep $BACKOFF
+              BACKOFF=$(( BACKOFF * 2 ))
+            else
+              echo "aria2c failed after $MAX_ATTEMPTS attempts—exiting."
+              exit 1
+            fi
+        done
+
+
+        dpkg -i "$PKG_TMPDIR/*.deb"
+        mv "$PKG_TMPDIR/*.deb" /var/cache/apt/archives
+        apt-get install -f -y
 
         echo /usr/lib/llvm-19/bin >> $GITHUB_PATH
       shell: bash
